Update FOD_API_Request.yaml
Updated the workflow file.

diff --git a/.github/workflows/FOD_API_Request.yaml b/.github/workflows/FOD_API_Request.yaml
--- a/.github/workflows/FOD_API_Request.yaml
+++ b/.github/workflows/FOD_API_Request.yaml
@@ -30,19 +30,21 @@ jobs:
            -H "Accept: application/json" \
            -w "%{http_code}" \
            -o "application-output.json") # Save the results of the query to a file
-          echo ""
           
           # Parses and Prints the response
           echo "API response saved to a JSON file. Showing all results from the query:"
           jq . application-output.json
-
-          echo "::set-output name=http_status::$HTTP_STATUS"
-
+          
     - name: Check API Response
       run: |
-          # Get the HTTP status code from the previous step's output
-          HTTP_STATUS="${{ steps.api_request.outputs.http_status }}"
+         # Prints the status code
+          echo "${HTTP_STATUS}"
 
-          # Print the HTTP status code
-          echo "HTTP Status Code: $HTTP_STATUS"
+          # Check if the status code is 200
+          if [ "${HTTP_STATUS}" -eq 200 ]; then
+            echo "API request was successful."
+          else
+            echo "API request failed with status code: $HTTP_STATUS"
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi
          
