Update FOD_API_Request.yaml

diff --git a/.github/workflows/FOD_API_Request.yaml b/.github/workflows/FOD_API_Request.yaml
--- a/.github/workflows/FOD_API_Request.yaml
+++ b/.github/workflows/FOD_API_Request.yaml
@@ -39,3 +39,13 @@ jobs:
           # Parses and Prints the response
           echo "API response saved to a JSON file. Showing all results from the query:"
           jq . application-output.json
+
+    - name: Check FOD API Response
+      run: |
+          # Check if the status code is 200
+          if [ "${HTTP_STATUS}" -eq 200 ]; then
+            echo "API request was successful."
+          else
+            echo "API request failed with status code: $HTTP_STATUS"
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi
