Update FOD_API_Request.yaml
Updated the workflow file.

diff --git a/.github/workflows/FOD_API_Request.yaml b/.github/workflows/FOD_API_Request.yaml
--- a/.github/workflows/FOD_API_Request.yaml
+++ b/.github/workflows/FOD_API_Request.yaml
@@ -25,14 +25,27 @@ jobs:
           echo "Repository Name: ${Repo_Name}"
           
           # Checks if an application exisits in Fortify On Demand Tenant and extracts the HTTP status code from the response 
-          curl -X GET "${FOD_API_URL}/applications?filters=applicationName%3A${Repo_Name}" \
+          Get_FOD_Application_Request=$(curl -X GET "${FOD_API_URL}/applications?filters=applicationName%3A${Repo_Name}" \
            -H "Authorization: Bearer ${FOD_API_TOKEN}" \
            -H "Accept: application/json" \
-           -w "%{http_code}" \
-           -o "application-output.json" # Save the results of the query to a file
+           --write-out "%{http_code}" \
+           -o "application-output.json") # Save the results of the query to a file
+
+           Request_Status_Code=$(echo $Get_FOD_Application_Request | tr -d '\n' | sed -e 's/.*Status Code://')
           
           # Parses and Prints the response
           echo "API response saved to a JSON file. Showing all results from the query:"
           jq . application-output.json
 
-         
+    - name: Check FOD API Response
+      run: |
+          # Prints the status code
+          echo "${Request_Status_Code}"
+
+          # Check if the status code is 200
+          if [ "${Request_Status_Code}" -eq 200 ]; then
+            echo "API request was successful."
+          else
+            echo "API request failed with status code: ${Request_Status_Code}"
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi
