Update FOD_API_Request.yaml
Updated the workflow file.

diff --git a/.github/workflows/FOD_API_Request.yaml b/.github/workflows/FOD_API_Request.yaml
--- a/.github/workflows/FOD_API_Request.yaml
+++ b/.github/workflows/FOD_API_Request.yaml
@@ -34,5 +34,17 @@ jobs:
           echo "API response saved to a JSON file. Showing all results from the query:"
           jq . application-output.json
 
+    - name: Check API Response
+      run: |
+          # Extract the HTTP status code from the response
+          HTTP_STATUS=$(tail -c 3 application-output.json)
+
+          # Check if the status code is 200
+          if [ "$HTTP_STATUS" == "200" ]; then
+            echo "API request was successful."
+          else
+            echo "API request failed with status code: $HTTP_STATUS"
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi
           
          
