Update fod_apps_manager.yaml

diff --git a/.github/workflows/fod_apps_manager.yaml b/.github/workflows/fod_apps_manager.yaml
--- a/.github/workflows/fod_apps_manager.yaml
+++ b/.github/workflows/fod_apps_manager.yaml
@@ -180,6 +180,86 @@ jobs:
             
             exit 1  # Exit with a non-zero status code to indicate failure
           fi
+
+  FOD-SAST-Scan-Options:
+    runs-on: ubuntu-latest
+    needs: FOD-Application-Management
+    env:
+      FOD_URL: "${{ secrets.FOD_URL }}"
+      FOD_API_URL: "${{ secrets.FOD_API_BASE_URL }}"
+      FOD_TENANT: ${{ secrets.FOD_TENANT }}
+      FOD_USER: ${{ secrets.FOD_USER }}
+      FOD_PAT: ${{ secrets.FOD_PAT }}
+      FOD_RELEASE_ID: ${{ needs.FOD-Application-Management.outputs.FOD_Release_ID }}
+         
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+
+    - name:  Setups up FOD Static Scan Options for the new Application
+      run: |
+          echo "Proceeding to set up SAST Scan options for your ${Repo_Name} Application in Fortify On Demand..."
+
+          # Creates a JSON file to be used as body for the Set Up of the SAST Scan options 
+          Save_FOD_Application_Static_Scan_Options_Body=$(cat <<-EOF
+          {
+            "assessmentTypeId": 274,
+            "entitlementId": 12880,
+            "entitlementFrequencyType": 2,
+            "releaseId": $FOD_Release_ID,
+            "technologyStackId": 22,
+            "technologyStack": "Go",
+            "languageLevelId": null,
+            "languageLevel": null,
+            "performOpenSourceAnalysis": false,
+            "auditPreferenceType": 2,
+            "includeThirdPartyLibraries": false
+          }
+          EOF
+          )
+
+          # Echo JSON data to a file named options.json
+          echo "$Save_FOD_Application_Static_Scan_Options_Body" > options.json
+
+          # Sends an API Request with PUT Method to set up the sast scan options of the recently created application
+          Save_FOD_Application_Static_Scan_Options_Request=$(curl -X PUT "${FOD_API_URL}/releases/${FOD_RELEASE_ID}/static-scans/scan-setup" \
+            -H "Authorization: Bearer ${FOD_API_TOKEN}" \
+            -H "Accept: application/json" \
+            -H "Content-Type: application/json" \
+            -w "%{http_code}" \
+            -o "save-sast-scan-options-output.json" \
+            -d @options.json)
+                
+          # Saves the PUT request's status code
+          Static_Scan_Options_Request_Status_Code=$(echo $Save_FOD_Application_Static_Scan_Options_Request | tr -d '\n' | sed -e 's/.*Status Code://')
+           
+          # Prints the status code of the POST Request
+          echo "Status code from the request of creation a FOD application: ${Static_Scan_Options_Request_Status_Code}"
+
+          # Checks if the status code of the request is 200 if not it will end the workflow with an error
+          if [[ $Static_Scan_Options_Request_Status_Code -eq 200 ]]; then
+            echo "API Request was successful."
+            
+            # Prints the status code of the PUT Request (Passed Request)
+            echo "Status code from the request of saving FOD application sast scan options: ${Static_Scan_Options_Request_Status_Code}"
+            
+            # Prints the response of the Put Request as a parsed JSON (Passed Request)
+            echo "API Request response saved to a JSON file. Showing the results from the query:"
+            jq . save-sast-scan-options-output.json
+          
+            echo "SAST scan options from ${Repo_Name} application has been saved."
+          else
+            echo "API Request has failed. FOD API server is down or your Token has expired or please check the POST Request"
+            
+            # Prints the status code of the PUT Request (Failed Request)
+            echo "Status code from the request of saving FOD application sast scan options: ${Static_Scan_Options_Request_Status_Code}"
+                
+            # Prints the response of the PUT Request as a parsed JSON (Failed Request)
+            echo "API Request response saved to a JSON file, please check the errors and fix the issue if needed:"
+            jq . save-sast-scan-options-output.json
+                
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi  
           
   FOD-SAST-Scan:
     # Use the appropriate runner for building your source code.
